### ISSUE TITLE
crash on 1.5.3

### ISSUE THREAD

**Issue by superawesome** [shadowhen89/EquipBestItem-Archive#1]
After fighting bandits (really they surrendered) and capturing them all, when I close the party screen to move on to the "loot" screen, I get this crash shown by BetterExceptionsWindow:

 - Reasons
Source: EquipBestItem

Method not found: 'Int32 TaleWorlds.Core.ItemModifier.ModifyHorseCharge(Int32)'.
- Inner exception
Source: No module

No inner exception was thrown
- Callstacks

Protip: Use a debugger like dnSpy or Visual studio to trace the source of error, by stepping the program line by line.
Inner exception callstack:

No inner exception was thrown

Outer exception callstack:

   at EquipBestItem.MainViewModel.ItemIndexCalculation(EquipmentElement sourceItem, EquipmentIndex slot)
   at EquipBestItem.MainViewModel.GetBetterItemFromSide(MBBindingList`1 itemListVM, EquipmentElement equipmentElement, EquipmentIndex slot, Boolean isCivilian, CharacterObject character)
   at EquipBestItem.MainViewModel.RefreshValues()
   at EquipBestItem.MainLayer.OnLateUpdate(Single dt)
   at TaleWorlds.Engine.Screens.ScreenManager.LateUpdate(Single dt)
   at TaleWorlds.Engine.Screens.ScreenManager.Tick_Patch1(Single dt)

**Comment by shadowhen** [comment]
Fixed in a [patch](https://www.nexusmods.com/mountandblade2bannerlord/mods/1996?tab=files).
